### ISSUE TITLE
Package is not installable

### ISSUE THREAD

**Issue by irasnyd** [LCOGT/lcogt-commissioning#4]
## Description of Issue

The `setup.py` is missing dependency information. This means that this code cannot be installed through the standard `python setup.py install` method or the `pip install git+https://github.com/LCOGT/lcogt-commissioning.git@master` method.

## What I expected to happen

I expected the package to be installed and work correctly, including all necessary dependencies.

## What happened

The package was installed, however none of the required dependencies were installed.

## Example
```
$ python3.7 -m venv env3
$ source env3/bin/activate
$ python -m pip install git+https://github.com/LCOGT/lcogt-commissioning.git@master
Collecting git+https://github.com/LCOGT/lcogt-commissioning.git@master
  Cloning https://github.com/LCOGT/lcogt-commissioning.git (to revision master) to /tmp/pip-req-build-9b76mqqi
Installing collected packages: lcocommissioning
  Running setup.py install for lcocommissioning ... done
Successfully installed lcocommissioning-2.0.11
$ ls env3/bin/
activate       analysegainhistory  easy_install-3.7  noisegainmef  pip3.7   python3.7            submitNRESObservation
activate.csh   crawlnoisegain      effocus           pip           python   sinistrocrosstalk    submitXtalkObservation
activate.fish  easy_install        focuscurve        pip3          python3  submitNamedModeTest
$ analysegainhistory -h
Traceback (most recent call last):
  File "/home/eng/isnyder/env3/bin/analysegainhistory", line 11, in <module>
    load_entry_point('lcocommissioning==2.0.11', 'console_scripts', 'analysegainhistory')()
  File "/home/eng/isnyder/env3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/eng/isnyder/env3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/eng/isnyder/env3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/eng/isnyder/env3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/eng/isnyder/env3/lib/python3.7/site-packages/noisegaincrawler/analysegainhistory.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

## Proposed Fix

I believe this package can be made installable by adding the dependencies to the `setup.py` configuration ([example here](https://github.com/LCOGT/pyallsky/blob/master/setup.py#L15)). Something like this:

```python
setuptools.setup(
  # ... all of the existing stuff ...
  install_requires=[
    'matplotlib==3.1.3',
    # whatever other dependencies this project has
  ],
)
```

## Why this will help

This will make it easier to build an automated installation script for this package.

**Comment by drhaz** [comment]
Should be fixed.

**Comment by irasnyd** [comment]
Excellent, thank you for fixing it so quickly!
